/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package io.nstudio.ngconf2021;

@com.tns.JavaScriptImplementation(javaScriptFile = "./index.js")
public class CustomActivity extends com.getcapacitor.BridgeActivity
    implements com.tns.NativeScriptHashCodeProvider {
  public CustomActivity() {
    super();
    com.tns.Runtime.initInstance(this);
  }

  protected void onCreate(android.os.Bundle param_0) {
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
  }

  public void onStop() {
    java.lang.Object[] args = new java.lang.Object[0];
    com.tns.Runtime.callJSMethod(this, "onStop", void.class, args);
  }

  public void onPictureInPictureModeChanged(boolean param_0) {
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    com.tns.Runtime.callJSMethod(this, "onPictureInPictureModeChanged", void.class, args);
  }

  public void onCreate(android.os.Bundle param_0, android.os.PersistableBundle param_1) {
    java.lang.Object[] args = new java.lang.Object[2];
    args[0] = param_0;
    args[1] = param_1;
    com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
  }

  protected void onUserLeaveHint() {
    java.lang.Object[] args = new java.lang.Object[0];
    com.tns.Runtime.callJSMethod(this, "onUserLeaveHint", void.class, args);
  }

  public void onPictureInPictureModeChanged(
      boolean param_0, android.content.res.Configuration param_1) {
    java.lang.Object[] args = new java.lang.Object[2];
    args[0] = param_0;
    args[1] = param_1;
    com.tns.Runtime.callJSMethod(this, "onPictureInPictureModeChanged", void.class, args);
  }

  public int hashCode__super() {
    return super.hashCode();
  }

  public boolean equals__super(java.lang.Object other) {
    return super.equals(other);
  }
}
